# Site settings
title: MANSI SINGH
description: I DON'T TAKE MEETINGS I SET THEM, MY RESPECT ISN'T DEMANDED, IT'S EARNED
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

header_img: assets/img/sad.jpg
# User settings
username: Mansi Singh
user_description: <h4>
" To work in a premier organisation which gives me ample opportunities to apply my skills, to grow and to contribute in the most effective manner by being a key and an effective team player. "</h4> <p>I am born and brought up in Pune,Maharashtra. Presently I am a BTech CSE student. I love to explore things as much as I can. This is the only reason which binds me with all work I do. My interest to explore the cyber world, always encourage me to work in this area and to learn new stuffs. Chose cyber security as the area of concentration to fulfill my dreams. Passionate to become a cyber forensic expert. Working hard and exploring the field to achieve it. Did some courses to reach my goal. Interested in hacking as well as enjoy other activities related to cyber security.</p><p>
Apart from being a cyber freek, I am passionate about dance. I also enjoy listening to music. Other than these I am crazy for adventurous sports like trekking, sky-diving and many more. I also play chess, pool, cricket. Travelling and food is what surprise me. New places, new people, new culture and delicious food is what keeps me going. I am fond of solving puzzles, mysteries as well as reading mystery novels.</p>
email: manasisingh67@gmail.com
twitter_username: manasisingh67
github_username:  manasisingh67
gplus_username:  +MansiSingh67

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
